# easier prefix (optional but highly recommended)
set -g prefix C-k
unbind C-b
bind C-k send-prefix

# use vim-style keys in copy mode
setw -g mode-keys vi

# split panes using | and -
bind | split-window -h
bind - split-window -v

# reload config quickly
bind r source-file ~/.tmux.conf \; display-message "reloaded"

# better pane navigation (no prefix needed)
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-j select-pane -D
bind -n C-k select-pane -U

bind Tab last-window

# Make new windows from current dir by default
bind c new-window -c "#{pane_current_path}"
