# easier prefix (optional but highly recommended)
set -g prefix C-k
unbind C-b
bind C-k send-prefix

# use vim-style keys in copy mode
setw -g mode-keys vi

# split panes using | and -
bind | split-window -h
bind - split-window -v

# reload config quickly
bind r source-file ~/.tmux.conf \; display-message "reloaded"

bind Tab last-window

# Make new windows from current dir by default
bind c new-window -c "#{pane_current_path}"
